### ISSUE TITLE
Mark read multiple entries parameters entry[0], entry[1], ...

### ISSUE THREAD

**Issue by pstuifzand** [aaronpk/Monocle#11]
It's seems Monocle uses entry[0], entry[1] as parameters for the mark_read action. Wouldn't it be simpler to use entry[], for all parameters. It would be more in line with the micropub spec, where there are two possibilities to send parameters: entry or entry[]. Now I have to support three different methods, with this one not being supported natively.

**Comment by aaronpk** [comment]
You're right, this is a bug with Monocle! You can thank PHP's http_build_query for that. I'll fix it in Monocle!

**Comment by aaronpk** [comment]
Yep you're right, Monocle should not be sending numeric indexes in the arrays. You can thank PHP's `http_build_query` for that. I just pushed up a fix!
