### ISSUE TITLE
Wrong response_type requested during login

### ISSUE THREAD

**Issue by cweiske** [aaronpk/Monocle#12]
I try to login to monocle and only have an auth endpoint. Monocle then warns me that I can only read, which is fine.
Continuing the login process, it still tries to login with a `response_type=code` instead of `id`.

**Comment by cweiske** [comment]
See https://github.com/indieweb/indieauth-client-php/issues/2

**Comment by aaronpk** [comment]
The fix for the indieauth client library has been deployed!
