### ISSUE TITLE
PuSH feeds for HTML without http headers don't work

### ISSUE THREAD

**Issue by bcomnes** [aaronpk/Monocle#15]
I added a PuSH hub to my html feed, and was already subscribed to this html feed in monocle.  It does not appear to have made the pubsubhubbub sub after the addition.

**Comment by bcomnes** [comment]
I'm not actually sure whats going on.

**Comment by aaronpk** [comment]
I think it's working now, I just added it to mine and it says it last received a ping from you on Apr 7.

**Comment by bcomnes** [comment]
Yeah everything looks good now.
