### ISSUE TITLE
Distributed-Indieauth

### ISSUE THREAD

**Issue by elf-pavlik** [aaronpk/Monocle#27]
http://indiewebcamp.com/distributed-indieauth#Sites_that_support_distributed_IndieAuth
lists Monocle

But when i try to use https://monocle.p3k.io/ with https://wwelves.org/perpetual-tripper it sends me to indieauth.com while my page has `<link rel="authorization_endpoint" href="https://indiecert.net/auth" />` which works fine with https://reader.kylewm.com

**Comment by aaronpk** [comment]
You should have seen a notice before you were taken to indieauth.com, "It looks like your site isn't pointing to a Micropub endpoint. You'll still be able to read with Monocle, but won't be able to use it to reply or to "like" things from your site."

Monocle first looks for Micropub support on your site, and if it's not found, uses indieauth.com for sign-in as a fallback. This allows people who don't support Micropub to still use Monocle.

**Comment by elf-pavlik** [comment]
Yes, I've seen this notice. Still I don't understand why it used indieauth.com instead of indiecert.net as I specify with `<link rel="authorization_endpoint" href="https://indiecert.net/auth" />`
