### ISSUE TITLE
Future posts get pinned to the top of the list

### ISSUE THREAD

**Issue by bcomnes** [aaronpk/Monocle#30]
If you accidentally post a blog post with a  future date, it remains at the top of the stream until that date.

**Comment by aaronpk** [comment]
I suppose if I ever encounter a future-dated post, I should cap it at "now"

**Comment by bcomnes** [comment]
yeah that seems better.

**Comment by tantek** [comment]
@bcomnes I'd say it's the publisher's responsibility to not put future posts into their home page stream/feed until the publication date of said future post. E.g.: http://indiewebcamp.com/future#Tantek

**Comment by bcomnes** [comment]
It was an accidental post with the wrong date in this case.  Even after correction, the post remained pinned.
