### ISSUE TITLE
Feature request: option to sign out

### ISSUE THREAD

**Issue by metbril** [aaronpk/Monocle#31]
After logging in, there is no option to sign out. This was needed after switching platforms for my site and using a different Auth provider.

As a workaround, I was able to delete all cookies from the cache.

Suggested location: the bottom of the sidebar on the lef.

**Comment by metbril** [comment]
I have discovered the hidden /logout page as a temporary workaround.

**Comment by jackjamieson2** [comment]
I second this request. I've been signing out with a plugin to remove cookies (https://addons.mozilla.org/en-US/firefox/addon/remove-cookies-button-ver1x/) , but a visible logout option would be preferable

**Comment by aaronpk** [comment]
Sorry! I lost the logout button when I removed the dashboard page. You can still visit `/logout` to log out until I add the button back.

**Comment by aaronpk** [comment]
There is a logout button at the bottom of the channel list now!
