### ISSUE TITLE
Feature: hide read items

### ISSUE THREAD

**Issue by metbril** [aaronpk/Monocle#32]
If I open a channel that has no unread items, or that has some old unread items left, I get to see all read items (first).

It would be nice to have a setting/toggle to hide read items.

**Comment by aaronpk** [comment]
This needs support from the Microsub server, here's the issue tracking that part of the spec https://github.com/indieweb/microsub/issues/24

**Comment by aaronpk** [comment]
There is now an option to show only unread entries. It's not the default, but you can at least now find unread items that might be buried under a bunch of read ones.
