### ISSUE TITLE
monocle.p3k.io not updating aubscriptions

### ISSUE THREAD

**Issue by diplix** [aaronpk/Monocle#33]
as far as i can see, monocle ceased updating subscriptions in mid december. seems as if the background worker process does not run.

<img width="766" alt="bildschirmfoto 2016-01-28 um 09 48 20" src="https://cloud.githubusercontent.com/assets/4541494/12639407/78c79dda-c5a4-11e5-8302-fcfb2b0f6092.png">

**Comment by aaronpk** [comment]
Thanks, you're right, not sure how that got stopped. Fixed now so it has a lot of catching up to do!
